### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'push')

### ISSUE THREAD

**Issue by heoyongun** [Junvary/quasar-app-extension-qstatistic#1]
Hello.

this is my package info.

  "dependencies": {
    "@quasar/extras": "^1.0.0",
    "axios": "^0.21.1",
    "pinia": "^2.0.11",
    "quasar": "^2.6.0",
    "vue": "^3.0.0",
    "vue-i18n": "^9.0.0",
    "vue-router": "^4.0.0",
    "xe-utils": "^3.5.7"
  },
  "devDependencies": {
    "@intlify/vite-plugin-vue-i18n": "^3.3.1",
    "@quasar/app-vite": "^1.0.0",
    "autoprefixer": "^10.4.2",
    "postcss": "^8.4.14",
    "quasar-app-extension-qstatistic": "^0.0.3"
  },

this is my error meeage

![스크린샷, 2022-11-16 16-13-47](https://user-images.githubusercontent.com/6076067/202111253-2a4e4e11-56ed-48cb-b281-e177f0417b50.png)

error point
![스크린샷, 2022-11-16 16-19-49](https://user-images.githubusercontent.com/6076067/202112718-2bed5951-c455-4abd-805d-586482136f67.png)

**Comment by Junvary** [comment]
Please try it with webpack and install with "quasar ext add qstatistic".
